//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace Meiam.System.Model {
    ///<summary>
    ///拉力机明细档案
    ///</summary>
    [SugarTable("INSPECT_TENSILE_D")]
    public class INSPECT_TENSILE_D {
        public INSPECT_TENSILE_D() {
        }

        /// <summary>
        /// 描述 : INSPECT_TENSILE_DID 
        /// 空值 : False
        /// 默认 : 
        /// </summary>
        [Display(Name = "INSPECT_TENSILE_DID")]
        [SugarColumn(IsPrimaryKey = true)]
        public string INSPECT_TENSILE_DID { get; set; }

        /// <summary>
        /// 描述 : ITEMID 
        /// 空值 : 可根据实际情况设置
        /// 默认 : 
        /// </summary>
        [Display(Name = "ITEMID")]
        public string ITEMID { get; set; }

        /// <summary>
        /// 描述 : LOTID 
        /// 空值 : 可根据实际情况设置
        /// 默认 : 
        /// </summary>
        [Display(Name = "LOTID")]
        public string LOTID { get; set; }

        /// <summary>
        /// 描述 : INSPECTCODE 
        /// 空值 : 可根据实际情况设置
        /// 默认 : 
        /// </summary>
        [Display(Name = "INSPECTCODE")]
        public string INSPECTCODE { get; set; }

        /// <summary>
        /// 描述 : ITEMNAME 
        /// 空值 : 可根据实际情况设置
        /// 默认 : 
        /// </summary>
        [Display(Name = "ITEMNAME")]
        public string ITEMNAME { get; set; }

        /// <summary>
        /// 描述 : TESTTYPE 
        /// 空值 : 可根据实际情况设置
        /// 默认 : 
        /// </summary>
        [Display(Name = "TESTTYPE")]
        public string TESTTYPE { get; set; }

        /// <summary>
        /// 描述 : INSPECTTYPE1 
        /// 空值 : 可根据实际情况设置
        /// 默认 : 
        /// </summary>
        [Display(Name = "INSPECTTYPE1")]
        public string INSPECTTYPE1 { get; set; }

        /// <summary>
        /// 描述 : INSPECT_DATE 
        /// 空值 : 可根据实际情况设置
        /// 默认 : 
        /// </summary>
        [Display(Name = "INSPECT_DATE")]
        public DateTime? INSPECT_DATE { get; set; }

        /// <summary>
        /// 描述 : PEOPLE02 
        /// 空值 : 可根据实际情况设置
        /// 默认 : 
        /// </summary>
        [Display(Name = "PEOPLE02")]
        public string PEOPLE02 { get; set; }

        /// <summary>
        /// 描述 : X-AXIS 
        /// 空值 : 可根据实际情况设置
        /// 默认 : 
        /// </summary>
        [Display(Name = "X-AXIS")]
        [SugarColumn(ColumnName = "X-AXIS")]
        public string X_AXIS { get; set; }

        /// <summary>
        /// 描述 : Y-AXIS 
        /// 空值 : 可根据实际情况设置
        /// 默认 : 
        /// </summary>
        [Display(Name = "Y-AXIS")]
        [SugarColumn(ColumnName = "Y-AXIS")]
        public string Y_AXIS { get; set; }

        /// <summary>
        /// 描述 : SAMPLEID 
        /// 空值 : 可根据实际情况设置
        /// 默认 : 
        /// </summary>
        [Display(Name = "SAMPLEID")]
        public string SAMPLEID { get; set; }

        /// <summary>
        /// 描述 : INSPECT_DEV1ID 
        /// 空值 : 可根据实际情况设置
        /// 默认 : 
        /// </summary>
        [Display(Name = "INSPECT_DEV1ID")]
        public string INSPECT_DEV1ID { get; set; }

        /// <summary>
        /// 描述 : Flag 
        /// 空值 : 可根据实际情况设置
        /// 默认 : 
        /// </summary>
        [Display(Name = "Flag")]
        public bool Flag { get; set; }

    }
}