//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------
using Meiam.System.Model;
using System.Threading.Tasks;
using System;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using Microsoft.Data.SqlClient;
using System.Data.Common;
using Microsoft.Extensions.Configuration;
using DocumentFormat.OpenXml.Office2013.Word;
using Meiam.System.Common;
using SqlSugar;
using System.Data;
using System.Linq;
using Newtonsoft.Json;

namespace Meiam.System.Interfaces
{
    public class MSService : BaseService<INSPECT_TENSILE_D>, IMSService
    {

        public MSService(IUnitOfWork unitOfWork) : base(unitOfWork)
        {
        }

        private readonly ILogger<MSService> _logger;
        private readonly string _connectionString;

        public MSService(IUnitOfWork unitOfWork, ILogger<MSService> logger) : base(unitOfWork)
        {
            _logger = logger;
        }

        #region ERP收料通知单
        public async Task<ApiResponse> ProcessLotNoticeAsync(List<LotNoticeRequest> requests)
        {
            _logger.LogInformation("开始处理收料通知单，共 {Count} 条", requests.Count);

            int successCount = 0;
            int failCount = 0;
            var errorMessages = new List<string>();

            try
            {
                // 按批号分组合并ENTRYID
                var groupedRequests = GroupAndMergeRequests(requests);

                _logger.LogInformation("批号分组后共 {GroupCount} 组数据", groupedRequests.Count);

                foreach (var request in groupedRequests)
                {
                    try
                    {
                        // 验证数据
                        if (request.LOT_QTY <= 0)
                        {
                            _logger.LogWarning("到货数量无效: {LotQty}", request.LOT_QTY);
                            throw new ArgumentException("到货数量必须大于0");
                        }

                        //判断重复
                        bool isExist = Db.Ado.GetInt($@"SELECT count(*) FROM INSPECT_IQC WHERE ENTRYID = '{request.ENTRYID}' AND KEEID = '{request.ID}' AND OrgID = '{request.ORGID}'") > 0;
                        if (isExist)
                        {
                            _logger.LogWarning($"收料通知单已存在: {request.ID}");
                            errorMessages.Add($"收料通知单已存在: {request.ID}");
                            failCount++;
                            continue;
                        }

                        // 检查是否已存在相同批号的记录
                        string batchKey = GetBatchKey(request);
                        bool istBatchExist = CheckBatchExists(batchKey);
                        if (istBatchExist)
                        {
                            _logger.LogInformation("批号已存在，执行更新操作: {BatchKey}", batchKey);
                            // 更新现有记录（合并ENTRYID和数量）
                            UpdateExistingRecord(request, batchKey);
                        }
                        else
                        {
                            _logger.LogInformation("批号不存在，执行插入操作: {BatchKey}", batchKey);
                            // 生成检验单号并插入新记录
                            var inspectionId = GenerateInspectionId();
                            _logger.LogInformation("生成检验单号: {InspectionId}", inspectionId);
                            InsertNewRecord(request, inspectionId);
                        }

                        successCount++;
                        await Task.Delay(10); // 模拟异步操作
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError("处理单条收料通知单失败: {ErrorMessage}", ex.Message);
                        errorMessages.Add($"处理单条收料通知单失败: {ex.Message}");
                        failCount++;
                        // 继续处理下一条，不中断整个批次
                    }
                }

                // 根据处理结果返回不同的响应
                if (successCount > 0 && failCount == 0)
                {
                    _logger.LogInformation("收料通知单全部处理成功，共 {SuccessCount} 条", successCount);
                    return new ApiResponse
                    {
                        Success = true,
                        Message = $"收料通知单接收成功，共处理 {successCount} 条数据"
                    };
                }
                else if (successCount > 0 && failCount > 0)
                {
                    _logger.LogWarning("收料通知单部分处理成功，成功 {SuccessCount} 条，失败 {FailCount} 条", successCount, failCount);
                    return new ApiResponse
                    {
                        Success = true, 
                        Message = $"收料通知单部分处理成功，成功 {successCount} 条，失败 {failCount} 条",
                        Data = errorMessages 
                    };
                }
                else
                {
                    _logger.LogError("收料通知单全部处理失败，共 {FailCount} 条", failCount);
                    return new ApiResponse
                    {
                        Success = false,
                        Message = $"收料通知单接收失败，所有 {failCount} 条数据处理失败",
                        Data = errorMessages 
                    };
                }

            }
            catch (Exception ex)
            {
                _logger.LogError("处理收料通知单批次失败: {ErrorMessage}", ex.Message);
                return new ApiResponse
                {
                    Success = false,
                    Message = $"收料通知单接收失败，原因：{ex.Message}"
                };
            }
        }

        /// <summary>
        /// 按批号分组并合并ENTRYID
        /// </summary>
        private List<LotNoticeRequest> GroupAndMergeRequests(List<LotNoticeRequest> requests)
        {
            var grouped = requests
                .GroupBy(r => GetBatchKey(r))
                .Select(g => new LotNoticeRequest
                {
                    ID = g.First().ID,
                    ENTRYID = g.First().ENTRYID, // 保留第一个ENTRYID
                    ENTRYIDS = string.Join(",", g.Select(x => x.ENTRYID).Distinct()), // 合并所有ENTRYID
                    ERP_ARRIVEDID = g.First().ERP_ARRIVEDID,
                    ITEMID = g.First().ITEMID,
                    ITEMNAME = g.First().ITEMNAME,
                    LOT_QTY = g.Sum(x => x.LOT_QTY), // 数量求和
                    LOTNO = g.First().LOTNO, // 取第一个批号
                    APPLY_DATE = g.First().APPLY_DATE,
                    MODEL_SPEC = g.First().MODEL_SPEC,
                    QUA_DATE = g.First().QUA_DATE,
                    PRO_DATE = g.First().PRO_DATE,
                    SUPPNAME = g.First().SUPPNAME,
                    LENGTH = g.First().LENGTH,
                    WIDTH = g.First().WIDTH,
                    INUM = g.Sum(x => x.INUM ?? 0), // 卷数求和
                    ORGID = g.First().ORGID,
                    SEQ = g.First().SEQ,
                    BUSINESSTYPE = g.First().BUSINESSTYPE
                })
                .ToList();

            return grouped;
        }

        /// <summary>
        /// 生成批号分组键
        /// </summary>
        private string GetBatchKey(LotNoticeRequest request)
        {
            // 获取批号最后一个"-"之前的部分
            string batchPrefix = request.LOTNO;
            if (!string.IsNullOrEmpty(request.LOTNO) && request.LOTNO.Contains("-"))
            {
                batchPrefix = request.LOTNO.Substring(0, request.LOTNO.LastIndexOf("-"));
            }

            // 组合键: ERP单号+物料ID+批号前缀
            return $"{request.ERP_ARRIVEDID}_{request.ITEMID}_{batchPrefix}";
        }

        /// <summary>
        /// 检查批号是否已存在
        /// </summary>
        private bool CheckBatchExists(string batchKey)
        {
            var parts = batchKey.Split('_');
            if (parts.Length < 3) return false;

            string erpArrivedId = parts[0];
            string itemId = parts[1];
            string lotPrefix = parts[2];

            string sql = @"
                SELECT COUNT(*) 
                FROM INSPECT_IQC 
                WHERE ERP_ARRIVEDID = @ErpArrivedId 
                  AND ITEMID = @ItemId 
                  AND LOTNO LIKE @LotPrefix + '%'";

            return Db.Ado.GetInt(sql, new
            {
                ErpArrivedId = erpArrivedId,
                ItemId = itemId,
                LotPrefix = lotPrefix
            }) > 0;
        }

        /// <summary>
        /// 生成检验单号
        /// </summary>
        private string GenerateInspectionId()
        {
            string INSPECT_CODE = "";//检验单号

            const string sql = @"
                DECLARE @INSPECT_CODE  	  NVARCHAR(200) 

                --获得IQC检验单号
                SELECT TOP 1 @INSPECT_CODE=CAST(CAST(dbo.getNumericValue(INSPECT_IQCCODE) AS DECIMAL)+1 AS CHAR)  FROM  INSPECT_IQC
                WHERE  TENID='001' AND ISNULL(REPLACE(INSPECT_IQCCODE,'IQC_',''),'') like REPLACE(CONVERT(VARCHAR(10),GETDATE(),120),'-','')+'%' 
                ORDER BY INSPECT_IQCCODE DESC

                IF(ISNULL(@INSPECT_CODE,'')='')
                   SET @INSPECT_CODE ='IQC_'+REPLACE(CONVERT(VARCHAR(10),GETDATE(),120),'-','')+'001'
                ELSE 
                   SET @INSPECT_CODE ='IQC_'+@INSPECT_CODE

                SELECT @INSPECT_CODE AS INSPECT_CODE
                ";

            // 执行 SQL 命令
            var dataTable = Db.Ado.GetDataTable(sql);
            if (dataTable.Rows.Count > 0)
            {
                INSPECT_CODE = dataTable.Rows[0]["INSPECT_CODE"].ToString().Trim();
            }
            return INSPECT_CODE;
        }

        /// <summary>
        /// 更新现有记录
        /// </summary>
        private void UpdateExistingRecord(LotNoticeRequest request, string batchKey)
        {
            string suppID = GetOrCreateSupplierId(request.SUPPNAME);

            string sql = @"
                UPDATE INSPECT_IQC 
                SET 
                    ENTRYIDS = CASE 
                        WHEN ENTRYIDS IS NULL THEN @EntryIds
                        WHEN CHARINDEX(@EntryIds, ENTRYIDS) = 0 THEN ENTRYIDS + ',' + @EntryIds
                        ELSE ENTRYIDS
                    END,
                    LOT_QTY = LOT_QTY + @LotQty,
                    INUM = ISNULL(INUM, 0) + @Inum,
                    ITEMNAME = @ItemName,
                    ITEM_SPECIFICATION = @ModelSpec,
                    SUPPID = @SuppID,
                    APPLY_DATE = @ApplyDate,
                    QUA_DATE = @QuaDate,
                    PRO_DATE = @ProDate,
                    LENGTH = @Length,
                    WIDTH = @Width
                WHERE ERP_ARRIVEDID = @ErpArrivedId 
                  AND ITEMID = @ItemId 
                  AND LOTNO LIKE @LotPrefix + '%'";

            var parts = batchKey.Split('_');
            string lotPrefix = parts.Length >= 3 ? parts[2] : "";

            var parameters = new SugarParameter[]
            {
                new SugarParameter("@EntryIds", request.ENTRYIDS),
                new SugarParameter("@LotQty", request.LOT_QTY),
                new SugarParameter("@Inum", request.INUM ?? 0),
                new SugarParameter("@ItemName", request.ITEMNAME),
                new SugarParameter("@ModelSpec", request.MODEL_SPEC),
                new SugarParameter("@SuppID", suppID),
                new SugarParameter("@ApplyDate", request.APPLY_DATE),
                new SugarParameter("@QuaDate", request.QUA_DATE),
                new SugarParameter("@ProDate", request.PRO_DATE),
                new SugarParameter("@Length", request.LENGTH),
                new SugarParameter("@Width", request.WIDTH),
                new SugarParameter("@ErpArrivedId", request.ERP_ARRIVEDID),
                new SugarParameter("@ItemId", request.ITEMID),
                new SugarParameter("@LotPrefix", lotPrefix)
            };

            Db.Ado.ExecuteCommand(sql, parameters);
        }

        /// <summary>
        /// 插入新记录
        /// </summary>
        public void InsertNewRecord(LotNoticeRequest request, string inspectionId)
        {
            string SuppID = GetOrCreateSupplierId(request.SUPPNAME);

            string sql = @"
                INSERT INTO INSPECT_IQC (
                    TENID, INSPECT_IQCID, INSPECT_IQCCREATEUSER, 
                    INSPECT_IQCCREATEDATE, ITEMNAME, ERP_ARRIVEDID, 
                    LOT_QTY, INSPECT_IQCCODE, ITEMID, LOTNO, 
                    APPLY_DATE, ITEM_SPECIFICATION, QUA_DATE,
                    PRO_DATE, LENGTH, WIDTH, SUPPID,
                    INUM, ENTRYID, ORGID, SEQ, BUSINESSTYPE,
                    KEEID, ENTRYIDS
                ) VALUES (
                    @TenId, @InspectIqcId, @InspectIqcCreateUser, 
                    getdate(), @ItemName, @ErpArrivedId,
                    @LotQty, @InspectIqcCode, @ItemId, @LotNo, 
                    @ApplyDate, @ItemSpecification, @QuaDate,
                    @ProDate, @Length, @Width, @SuppID,
                    @Inum, @EntryId, @OrgId, @Seq, @BusinessType,
                    @KeeId, @EntryIds
                )";

            // 定义参数
            var parameters = new SugarParameter[]
            {
                new SugarParameter("@TenId", "001"),
                new SugarParameter("@InspectIqcId", inspectionId),
                new SugarParameter("@InspectIqcCreateUser", "system"),
                new SugarParameter("@ItemName", request.ITEMNAME),
                new SugarParameter("@ErpArrivedId", request.ERP_ARRIVEDID),
                new SugarParameter("@LotQty", request.LOT_QTY),
                new SugarParameter("@InspectIqcCode", inspectionId),
                new SugarParameter("@ItemId", request.ITEMID),
                new SugarParameter("@LotNo", (request.LOTNO==null?"":request.LOTNO.ToString())),
                new SugarParameter("@ApplyDate", request.APPLY_DATE),
                new SugarParameter("@ItemSpecification", request.MODEL_SPEC),
                new SugarParameter("@QuaDate", request.QUA_DATE),
                new SugarParameter("@ProDate", request.PRO_DATE),
                new SugarParameter("@Length", request.LENGTH),
                new SugarParameter("@Width", request.WIDTH),
                new SugarParameter("@SuppID", SuppID),
                new SugarParameter("@Inum", request.INUM),
                new SugarParameter("@EntryId", request.ENTRYID),
                new SugarParameter("@OrgId", request.ORGID),
                new SugarParameter("@Seq", request.SEQ),
                new SugarParameter("@BusinessType", request.BUSINESSTYPE),
                new SugarParameter("@KeeId", request.ID),
                new SugarParameter("@EntryIds", request.ENTRYIDS)
            };

            // 执行 SQL 命令
            Db.Ado.ExecuteCommand(sql, parameters);
        }

        /// <summary>
        /// 获取或创建供应商ID
        /// </summary>
        private string GetOrCreateSupplierId(string suppName)
        {
            string SuppID = Db.Ado.GetScalar($@"SELECT TOP 1 SUPPID FROM SUPP WHERE SUPPNAME = '{suppName}'")?.ToString().Trim();

            if (string.IsNullOrEmpty(SuppID))
            {
                SuppID = Db.Ado.GetScalar($@"select TOP 1 cast(cast(dbo.getNumericValue(SUPPID) AS DECIMAL)+1 as char) from SUPP order by SUPPID desc")?.ToString().Trim();
                if (string.IsNullOrEmpty(SuppID))
                {
                    SuppID = "1001";
                }
                Db.Ado.ExecuteCommand($@"
                    INSERT INTO SUPP (
                        TENID, SUPPID, SUPP0A17, SUPPCREATEUSER, SUPPCREATEDATE,
                        SUPPMODIFYDATE, SUPPMODIFYUSER, SUPPCODE, SUPPNAME
                    )VALUES (
                        '001', '{SuppID}', '001', 'system', '{DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss.fff")}',
                        '{DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss.fff")}', 'system', '{SuppID}', '{suppName}')"
                    );
            }
            return SuppID;
        }
        #endregion

        #region 首检单据 
        public async Task<ApiResponse> ProcessWorkOrderAsync(List<WorkOrderSyncRequest> requests)
        {
            _logger.LogInformation("开始同步工单首检数据");

            try
            {
                foreach (var request in requests)
                {
                    // 验证数据
                    ValidateRequest(request);

                    //判断重复
                    bool isExist = Db.Ado.GetInt($@"SELECT count(*) FROM INSPECT_FPI WHERE MESFirstInspectID = '{request.ID}' AND MOID = '{request.MOID}' AND OrgID = '{request.ORGID}'") > 0;
                    if (isExist)
                    {
                        _logger.LogWarning($"首检单据已存在: {request.ID}");
                        continue;
                    }

                    // 生成FPI检验单号
                    var inspectionFpiId = GenerateInspectionFpiId();
                    _logger.LogInformation("生成检验单号: {InspectionFpiId}", inspectionFpiId);

                    // 业务处理
                    _logger.LogDebug("正在处理首检单据...");
                    ProcessFirstArticleInspection(request, inspectionFpiId);

                    await Task.Delay(10);
                    _logger.LogInformation("工单首检数据同步成功，工单号: {MOID}", request.MOID);
                }
                _logger.LogInformation("工单首检数据同步完成!");
                return new ApiResponse
                {
                    Success = true,
                    Message = "MES 工单数据同步成功",
                };
            }
            catch (Exception ex)
            {
                return new ApiResponse
                {
                    Success = false,
                    Message = $"MES 工单数据同步失败：{ex.Message}"
                };
            }
        }

        private void ValidateRequest(WorkOrderSyncRequest request)
        {
            if (string.IsNullOrWhiteSpace(request.MOID))
                throw new ArgumentException("缺少工单号");

            if (!DateTime.TryParse(request.CREATEDATE, out _))
                throw new ArgumentException("无效的日期格式");
        }

        private string GenerateInspectionFpiId()
        {
            string INSPECT_CODE = "";//检验单号

            const string sql = @"
                DECLARE @INSPECT_CODE  	  NVARCHAR(200) 

                --获得FPI检验单号
                SELECT TOP 1 @INSPECT_CODE=CAST(CAST(dbo.getNumericValue(INSPECT_FPICODE) AS DECIMAL)+1 AS CHAR)  FROM  INSPECT_FPI
                WHERE  TENID='001' AND ISNULL(REPLACE(INSPECT_FPICODE,'FAI_',''),'') like REPLACE(CONVERT(VARCHAR(10),GETDATE(),120),'-','')+'%' 
                ORDER BY INSPECT_FPICODE DESC

                IF(ISNULL(@INSPECT_CODE,'')='')
                   SET @INSPECT_CODE ='FAI_'+REPLACE(CONVERT(VARCHAR(10),GETDATE(),120),'-','')+'001'
                ELSE 
                   SET @INSPECT_CODE ='FAI_'+@INSPECT_CODE

                SELECT @INSPECT_CODE AS INSPECT_CODE
                ";

            // 执行 SQL 命令
            var dataTable = Db.Ado.GetDataTable(sql);
            if (dataTable.Rows.Count > 0)
            {
                INSPECT_CODE = dataTable.Rows[0]["INSPECT_CODE"].ToString().Trim();
            }
            return INSPECT_CODE;
        }

        public void ProcessFirstArticleInspection(WorkOrderSyncRequest request, string inspectionFpiId)
        {
            try
            {
                // 保存数据
                SaveMainInspectionFpi(request, inspectionFpiId);
            }
            catch
            {
                throw;
            }
        }

        private void SaveMainInspectionFpi(WorkOrderSyncRequest request, string inspectionFpiId)
        {
            const string sql = @"
                INSERT INTO INSPECT_FPI (
                    TENID, INSPECT_FPIID, INSPECT_FPICREATEUSER, 
                    INSPECT_FPICREATEDATE, MOID, INSPECT_FPICODE, 
                    ITEMNAME, ITEMID, ITEM04, MESFIRSTINSPECTID, ORGID
                ) VALUES (
                    @TenId, @InspectFpiId, @InspectFpiCreateUser, 
                    @InspectFpiCreateDate, @MoId, @InspectFpiCode,
                    @ItemName, @ItemId, @ITEM04, @MesFirstInspectId, @OrgId
                )";

            // 定义参数
            var parameters = new SugarParameter[]
            {
                new SugarParameter("@TenId", "001"),
                new SugarParameter("@InspectFpiId", inspectionFpiId),
                new SugarParameter("@InspectFpiCreateUser", "system"),
                new SugarParameter("@InspectFpiCreateDate", request.CREATEDATE),
                new SugarParameter("@MoId", request.MOID),
                new SugarParameter("@InspectFpiCode", inspectionFpiId),
                new SugarParameter("@ItemName", request.ITEMNAME),
                new SugarParameter("@ItemId", request.ITEMID),
                new SugarParameter("@ITEM04", request.MODEL_SPEC),
                new SugarParameter("@MesFirstInspectId", request.ID),
                new SugarParameter("@OrgId", request.ORGID)
            };

            // 执行 SQL 命令
            Db.Ado.ExecuteCommand(sql, parameters);
        }
        #endregion

        #region 产品检验结果(入库检) 
        public async Task<CheckResultResponse> ProcessLotCheckResult(LotCheckResultRequest request)
        {
            _logger.LogInformation("开始查询检验结果，料号: {ITEMID}", request.ITEMID);

            try
            {
                // 1. 参数验证
                ValidateRequest(request);

                // 2. 查询数据库
                var result = QueryLotCheckResult(request);

                await Task.Delay(10);
                _logger.LogDebug("检验结果查询成功，状态: {Result}", result);

                return new CheckResultResponse
                {
                    Success = (result == "合格" ? true : false),
                    Message = "调用成功",
                    Result = MapStateToResult(result)
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "检验结果查询失败");
                return new CheckResultResponse
                {
                    Success = false,
                    Message = $"API调用失败：{ex.Message}",
                };
            }
        }

        private void ValidateRequest(LotCheckResultRequest request)
        {
            if (string.IsNullOrWhiteSpace(request.ITEMID))
                throw new ArgumentException("缺少料号");
        }

        private string QueryLotCheckResult(LotCheckResultRequest request)
        {
            var sql = @"SELECT OQC_STATE
                FROM INSPECT_SI
                WHERE ITEMID = @ItemId
                  AND CONVERT(varchar(10), INSPECT_SINAME, 120) = @CheckDate
                  AND ORGID = @OrgId";

            // 定义参数
            var parameters = new SugarParameter[]
            {
                new SugarParameter("@ItemId", request.ITEMID),
                new SugarParameter("@CheckDate", request.CHECKDATE),
                new SugarParameter("@OrgId", request.ORGID)
            };

            // 执行 SQL 命令
            var state = Db.Ado.GetString(sql, parameters);
            return state;
        }

        private string MapStateToResult(string state)
        {
            return state switch
            {
                "PSTATE_005" => "合格",
                "PSTATE_006" => "合格",
                "PSTATE_008" => "合格",
                "PSTATE_007" => "不合格",
                _ => "未检验"
            };
        }
        #endregion

        #region ERP物料数据同步 
        public async Task<MaterialSyncResponse> ProcessMaterialSyncBatch(List<MaterialSyncItem> materials)
        {
            _logger.LogInformation("开始同步物料数据，共 {Count} 条", materials.Count);

            var response = await BatchSyncMaterialsAsync(materials);

            if (response.FailedCount > 0)
            {
                _logger.LogWarning("物料同步完成，失败 {FailedCount} 条", response.FailedCount);
            }
            else
            {
                _logger.LogInformation("物料同步全部成功");
            }

            return response;
        }

        public async Task<MaterialSyncResponse> BatchSyncMaterialsAsync(List<MaterialSyncItem> materials)
        {
            var response = new MaterialSyncResponse
            {
                TotalCount = materials.Count
            };

            try
            {
                foreach (var item in materials)
                {
                    try
                    {
                        // 1. 获取现有ORG列表
                        var existingOrgs = GetExistingOrgs(item.ITEMID);

                        // 2. 合并新旧ORGID（自动去重）
                        item.ORGID = MergeOrgIds(existingOrgs, item.ORGID);

                        // 3. 同步数据
                        SyncItemTable(item);

                        response.SuccessCount++;
                    }
                    catch (Exception ex)
                    {
                        response.Details.Add(new MaterialSyncDetail
                        {
                            ITEMID = item.ITEMID,
                            Error = ex.Message
                        });
                        response.FailedCount++;
                    }
                }

                if (response.FailedCount == 0)
                {
                    await Db.Ado.CommitTranAsync();
                    response.Success = true;
                    response.Message = $"共{response.TotalCount}条数据，同步成功{response.SuccessCount}条，失败{response.FailedCount}条";
                }
                else
                {
                    await Db.Ado.RollbackTranAsync();
                    response.Success = false;
                    response.Message = $"共{response.TotalCount}条数据，同步成功{response.SuccessCount}条，失败{response.FailedCount}条";
                }
            }
            catch
            {
                await Db.Ado.RollbackTranAsync();
                throw;
            }

            return response;
        }

        private string GetExistingOrgs(string itemId)
        {
            string sql = @"
            SELECT ORGID
            FROM ITEM 
            WHERE ITEMID = @ItemId";

            // 定义参数
            var parameters = new SugarParameter[]
            {
                new SugarParameter("@ItemId", itemId)
            };
            var dataTable = Db.Ado.GetDataTable(sql, parameters);

            if (dataTable.Rows.Count > 0)
            {
                return string.Join(";", dataTable.AsEnumerable()
                          .Select(row => row["ORGID"].ToString())); ;
            }
            else
            {
                return null;
            }
        }

        private string MergeOrgIds(string existingOrgs, string newOrgs)
        {
            var orgSet = new HashSet<string>(
                (existingOrgs ?? "").Split(';', StringSplitOptions.RemoveEmptyEntries));

            foreach (var org in (newOrgs ?? "").Split(';', StringSplitOptions.RemoveEmptyEntries))
            {
                orgSet.Add(org.Trim());
            }

            return string.Join(";", orgSet.OrderBy(x => x));
        }

        private void SyncItemTable(MaterialSyncItem item)
        {
            string sql = @"
                    MERGE INTO ITEM AS target
                    USING (SELECT @ItemId AS ITEMID, @ItemName AS ITEMNAME, @ITEM04 AS ITEM04, @ORGID AS ORGID) AS source
                    ON target.ITEMID = source.ITEMID
                    WHEN MATCHED THEN
                        UPDATE SET ITEMNAME = source.ITEMNAME,
                                   ITEM04 = source.ITEM04,
                                   ORGID = source.ORGID,
                                   ITEMCREATEDATE = getdate()
                    WHEN NOT MATCHED THEN
                        INSERT (ITEMID, ITEMCODE, ITEMNAME, ITEM04, ORGID, ITEMCREATEUSER, ITEMCREATEDATE)
                        VALUES (source.ITEMID, source.ITEMID, source.ITEMNAME, source.ITEM04, source.ORGID, 'system', getdate());";
            // 定义参数
            var parameters = new SugarParameter[]
            {
                new SugarParameter("@ItemId", item.ITEMID),
                new SugarParameter("@ItemName", item.ITEMNAME),
                new SugarParameter("@ORGID", item.ORGID),
                new SugarParameter("@ITEM04", item.MODEL_SPEC)
            };

            Db.Ado.ExecuteCommand(sql, parameters);
        }

        #endregion

        #region ERP客户同步 
        public async Task<CustomerSyncResponse> ProcessCustomersSynBatch(List<CustomerSyncItem> customers)
        {
            _logger.LogInformation("开始同步客户数据，数量: {Count}", customers?.Count);

            if (customers == null || customers.Count == 0)
            {
                _logger.LogWarning("接收到空客户列表");
                return new CustomerSyncResponse
                {
                    Success = false,
                    Message = "客户列表不能为空",
                    TotalCount = 0
                };
            }

            var response = await BatchSyncCustomersAsync(customers);

            if (response.FailedCount > 0)
            {
                _logger.LogWarning("客户同步完成，失败 {FailedCount} 条", response.FailedCount);
            }
            else
            {
                _logger.LogInformation("客户同步全部成功");
            }

            return response;
        }

        public async Task<CustomerSyncResponse> BatchSyncCustomersAsync(List<CustomerSyncItem> customers)
        {
            var response = new CustomerSyncResponse { TotalCount = customers.Count };

            try
            {
                foreach (var customer in customers)
                {
                    try
                    {
                        // 1. 获取现有ORG列表
                        var existingOrgsInCustomer = GetExistingOrgsInCustom(customer.CUSTOMCODE);

                        // 2. 合并新旧ORGID（自动去重）
                        customer.ORGID = MergeOrgIdsInCustom(existingOrgsInCustomer, customer.ORGID);

                        // 3. 同步数据
                        SyncCustomerTable(customer);

                        // 同步表
                        //await SyncCustomerTable(connection, transaction, customer);

                        response.SuccessCount++;
                    }
                    catch (Exception ex)
                    {
                        response.Details.Add(new CustomerSyncDetail
                        {
                            CUSTOMCODE = customer.CUSTOMCODE,
                            Error = ex.Message
                        });
                        response.FailedCount++;
                    }
                }

                response.Message = $"共{response.TotalCount}条数据，同步成功{response.SuccessCount}条，失败{response.FailedCount}条";
                response.Success = response.FailedCount == 0;

                if (response.Success)
                    await Db.Ado.CommitTranAsync();
                else
                    await Db.Ado.RollbackTranAsync();

                return response;
            }
            catch
            {
                await Db.Ado.RollbackTranAsync();
                throw;
            }
        }

        private string GetExistingOrgsInCustom(string customCode)
        {
            string sql = @"
                SELECT ORGID
                FROM CUSTOM 
                WHERE CUSTOMID = @CustomId";

            // 定义参数
            var parameters = new SugarParameter[]
            {
                new SugarParameter("@CustomId", customCode)
            };
            var dataTable = Db.Ado.GetDataTable(sql, parameters);

            if (dataTable.Rows.Count > 0)
            {
                return string.Join(";", dataTable.AsEnumerable()
                          .Select(row => row["ORGID"].ToString())); ;
            }
            else
            {
                return null;
            }
        }

        private string MergeOrgIdsInCustom(string existingOrgsInCustomer, string newOrgs)
        {
            var orgSet = new HashSet<string>(
                (existingOrgsInCustomer ?? "").Split(';', StringSplitOptions.RemoveEmptyEntries));

            foreach (var org in (newOrgs ?? "").Split(';', StringSplitOptions.RemoveEmptyEntries))
            {
                orgSet.Add(org.Trim());
            }

            return string.Join(";", orgSet.OrderBy(x => x));
        }

        private void SyncCustomerTable(CustomerSyncItem item)
        {
            string sql = @"
                MERGE INTO CUSTOM AS target
                USING (SELECT @CustomId AS CUSTOMID, @CustomName AS CUSTOMNAME, @ORGID AS ORGID) AS source
                ON target.CUSTOMID = source.CUSTOMID
                WHEN MATCHED THEN
                    UPDATE SET CUSTOMNAME = source.CUSTOMNAME,
                                ORGID = source.ORGID,
                                CUSTOMCREATEDATE = getdate()
                WHEN NOT MATCHED THEN
                    INSERT (CUSTOMID, CUSTOMCODE, CUSTOMNAME, ORGID, CUSTOMCREATEUSER, CUSTOMCREATEDATE)
                    VALUES (source.CUSTOMID, source.CUSTOMID, source.CUSTOMNAME, source.ORGID, 'system', getdate());";
            // 定义参数
            var parameters = new SugarParameter[]
            {
                new SugarParameter("@CustomId", item.CUSTOMCODE),
                new SugarParameter("@CustomName", item.CUSTOMNAME),
                new SugarParameter("@ORGID", item.ORGID)
            };

            Db.Ado.ExecuteCommand(sql, parameters);
        }
        #endregion

        #region 回写ERP MES方法
        public List<LotNoticeResultRequest> GetQmsLotNoticeResultRequest()
        {
            var sql = @"SELECT TOP 100 
                            KEEID AS ID,
                            ISNULL(ENTRYIDS, ENTRYID) AS FEntryIDs, -- 优先使用ENTRYIDS，如果没有则使用ENTRYID
                            ERP_ARRIVEDID AS BillNo, 
                            INSPECT_IQCCODE AS InspectBillNo,
                            ORGID AS OrgID,
                            CASE WHEN OQC_STATE IN ('OQC_STATE_005', 'OQC_STATE_006', 'OQC_STATE_008') THEN 1 ELSE 0 END AS Result,
                            ISNULL(TRY_CAST(FQC_CNT AS INT), 0) AS OKQty,       -- 不可转换时返回0
                            ISNULL(TRY_CAST(FQC_NOT_CNT AS INT), 0) AS NGQty     -- 不可转换时返回0
                        FROM INSPECT_IQC
                        WHERE (ISSY <> '1' OR ISSY IS NULL) 
                            AND OQC_STATE IN ('OQC_STATE_005', 'OQC_STATE_006', 'OQC_STATE_007', 'OQC_STATE_008')
                        ORDER BY INSPECT_IQCCREATEDATE DESC;";

            var list = Db.Ado.SqlQuery<LotNoticeResultRequest>(sql);
            return list;
        }
        public void CallBackQmsLotNoticeResult(LotNoticeResultRequest request)
        {
            var sql = string.Format(@"update INSPECT_IQC set ISSY='1' where KEEID='{0}' and ENTRYID='{1}' and OrgID='{2}' ", request.ID, request.EntryID, request.OrgID);
            Db.Ado.ExecuteCommand(sql);
        }


        public List<WorkOrderResultRequest> GetQmsWorkOrderResultRequest()
        {
            var sql = @"select top 100 MOID as BillNo,MESFirstInspectID,OrgID,OQC_STATE,
                        (case when OQC_STATE in ('OQC_STATE_005','OQC_STATE_006','OQC_STATE_007','OQC_STATE_008') then 1 else 0 end) as Result 
                        from INSPECT_FPI
                        where (ISSY<>'1' or ISSY IS NULL) AND 
                        OQC_STATE in ('OQC_STATE_005','OQC_STATE_006','OQC_STATE_007','OQC_STATE_008') order by INSPECT_FPICREATEDATE desc";

            var list = Db.Ado.SqlQuery<WorkOrderResultRequest>(sql);
            return list;
        }
        public void CallBackQmsWorkOrderResult(List<WorkOrderResultRequest> requests)
        {
            foreach (var request in requests)
            {
                var sql = string.Format(@"update INSPECT_FPI set ISSY='1' where MOID='{0}' and MESFirstInspectID='{1}' and OrgID='{2}' ", request.BillNo, request.MESFirstInspectID, request.OrgID);
                Db.Ado.ExecuteCommand(sql);
            }
        }
        #endregion
    }
}
