//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------
using Meiam.System.Model;
using Meiam.System.Model.Dto;
using System.Collections.Generic;
using System.Threading.Tasks;
using SqlSugar;
using System.Linq;
using System;
using System.Data;

namespace Meiam.System.Interfaces
{
    /// <summary>
    /// 恒铭达
    /// </summary>
    public interface IHMDService : IBaseService<INSPECT_TENSILE_D>
    {
        Task<ApiResponse> GetInspectSpecDataAsync(INSPECT_SYSM002_REQBYID input);
        Task<ApiResponse> GetInspectInfoByDocCodeAsync(INSPECT_REQCODE input);
        Task<ApiResponse> GetProgressDataByDocCodeAsync(INSPECT_REQCODE input);
        Task<ApiResponse> ProcessHMDInpectDev1DataAsync(InspectDev1Entity input);
        Task<ApiResponse> GetInspectInfoByConditionAsync(INSPECT_CONDITION input);
        Task<ApiResponse> ProcessHMDInpectProcessDataAsync(List<INSPECT_PROGRESSDto> input);
        Task<ApiResponse> GetInspectInfoByRoshConditionAsync(INSPECT_CONDITION input);
        Task<ApiResponse> ProcessHMDInpectProcessRoshDataAsync(HMDRoshDataDto input);

        /// <summary>
        /// 同步收货数据
        /// </summary>
        Task SyncRcDataAsync();

        /// <summary>
        /// 同步报工数据
        /// </summary>
        Task SyncWrDataAsync();

        /// <summary>
        /// 同步物料数据
        /// </summary>
        Task SyncItemDataAsync();

        /// <summary>
        /// 同步供应商数据
        /// </summary>
        Task SyncVendDataAsync();

        /// <summary>
        /// 同步客户数据
        /// </summary>
        Task SyncCustDataAsync();

        /// <summary>
        /// 获取上次同步时间
        /// </summary>
        string GetLastSyncTime(string tableName, string timeFieldName);

        Task UpdateReceiveInspectResult();
        Task TestUpdateReceiveInspectResult(string requestXml);

        Task UpdateFqcResult();
    }
}
