//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------
using Meiam.System.Model;
using Meiam.System.Model.Dto;
using System.Collections.Generic;
using System.Threading.Tasks;
using SqlSugar;
using System.Linq;
using System;
using System.Data;

namespace Meiam.System.Interfaces
{
    public interface IIQCService : IBaseService<INSPECT_TENSILE> {

        #region CustomInterface 
        void GetCPKfile(string INSPECT_DEV2ID, string userName);
        void GetInspectBatchReport(InspectInputByCodeDto parm);
        void GetInspectReport(InspectInputDto parm);
        void GetBatchCPKfile(CPKInputByCodeDto parm);

        void ReplaceFTIRPdf(FTIRInputDto parm);
        void GetCOCfile(COCInputDto parm);
        DataSet GetCOCDataSource(COCInputDto parm);
        #endregion
    }
}
