//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------
using Meiam.System.Model;
using Meiam.System.Model.Dto;
using System.Collections.Generic;
using System.Threading.Tasks;
using SqlSugar;
using System.Linq;
using System;
using System.Data;

namespace Meiam.System.Interfaces
{
    public interface IMSService : IBaseService<INSPECT_TENSILE_D>
    {
        /// <summary>
        /// ERP收料通知单
        /// </summary>
        /// <param name="request">收料通知单请求数据</param>
        /// <returns>处理结果</returns>
        Task<ApiResponse> ProcessLotNoticeAsync(LotNoticeRequest request);

        /// <summary>
        /// 首检单据
        /// </summary>
        /// <param name="request">首检单据请求数据</param>
        /// <returns>处理结果</returns>
        Task<ApiResponse> ProcessWorkOrderAsync(WorkOrderSyncRequest request);
    }
}
